//Account Actions
export const SET_USER_DATA = 'SET_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const SET_INITIAL_ACCOUNT_DATA = 'SET_INITIAL_ACCOUNT_DATA';
export const SET_CURRENT_ACCOUNT_INDEX = 'SET_CURRENT_ACCOUNT_INDEX';

